---
- name: Install Microsoft apt key
  apt_key:
    url: "{{ powershell_microsoft_apt_key }}"
    state: present
  become: yes
- name: Install official Powershell repository
  apt_repository:
    repo: "{{ powershell_apt_repository[ansible_distribution_release] }}"
    state: present
  become: yes
