---
- name: Install required dependencies
  apt:
    name: "{{ powershell_apt_install_dependencies }}"
    state: present
  become: yes
- include_tasks: debian-ubuntu.yml
  when: ansible_distribution == "Ubuntu" or (ansible_distribution == "Debian")
- name: Install powershell
  apt:
    name: "{{ powershell_package_name }}"
    state: present
    update_cache: yes
  become: yes